---
title: "Laboratório 5"
author: "Leonardo Alves Godoy"
date: "29 de janeiro de 2016"
output: html_document
---

# purple_wave.jpg

O modelo linear teve um desempenho melhor.

Acredito que o padrão de transição pode ter ajudado, pois vai mudando "aos poucos" um valor em relação ao outro (r e b por exemplo) e o modelo capta essa transição.

```{r}
library(ggplot2)
library(magrittr)
library(tidyr)
library(dplyr)
library(jpeg)
library(tree)

img <- readJPEG("images/purple_wave.jpg")
img_dim <- dim(img)

# RGB para data.frame
img_df <- data.frame(
  x = rep(1:img_dim[2], each = img_dim[1]),
  y = rep(img_dim[1]:1, img_dim[2]),
  r = as.vector(img[,,1]),
  g = as.vector(img[,,2]),
  b = as.vector(img[,,3])
) %>%
  mutate(cor = rgb(r, g, b),
         id = 1:n())

# para reprodução
set.seed(1) 

# Parte 1) x, y, r, g
img_df_parte1 <- img_df %>% 
  sample_frac(3/5) %>% # separando 3/5 do banco
  mutate(b_backup = b, # backup do azul original
         b = 0, # retirando o azul da imagem
         cor = rgb(r, g, b)) # cor da imagem sem o azul

# Parte 2) x, y, r, g, b
img_df_parte2 <- img_df %>% filter(!id%in%img_df_parte1$id) # filtra as linhas que estão na Parte 1

# Imagem sem o azul
ggplot(data = img_df_parte1, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte1$cor) +
  labs(x = "x", y = "y", title = "Imagem sem B (azul)") +
  coord_fixed(ratio = 1) +
  theme_bw()

# Apenas o azul da imagem
ggplot(data = img_df_parte2, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte2$cor) +
  labs(x = "x", y = "y", title = "Imagem sem B (azul)") +
  coord_fixed(ratio = 1) +
  theme_bw()

# uma amostra de 500 pontos para a análise descritiva (usar o banco inteiro é desnecessário e demorado)
img_df_amostra <- img_df %>% 
  sample_n(500,replace = FALSE)

cor(img_df_amostra %>% 
      select (-cor, -id)) %>% 
  round(2)

pairs(~x + y + r + g + b, img_df_amostra )

modelo_lm <- lm(b ~ r, img_df_parte2)
modelo_tree <- tree( b ~ r, img_df_parte2)

predito_lm <- predict( modelo_lm, img_df_parte1)
predito_tree <- predict( modelo_tree, img_df_parte1)

img_df_parte1_lm <- img_df_parte1

img_df_parte1_lm$b <- predito_lm

img_df_parte1_lm$b[img_df_parte1_lm$b < 0] = 0

img_df_parte1_tree <- img_df_parte1

img_df_parte1_tree$b <- predito_tree

img_df_parte1_tree$predito_tree[img_df_parte1_tree$b < 0] = 0

mean(sum((img_df_parte1_lm$b_backup - img_df_parte1_lm$b)^2))

mean(sum((img_df_parte1_tree$b_backup - img_df_parte1_tree$b)^2))

jpg_predito_lm <- rgb(img_df_parte1_lm$r, img_df_parte1_lm$g, img_df_parte1_lm$b)

jpg_predito_tree <- rgb(img_df_parte1_tree$r, img_df_parte1_tree$g, img_df_parte1_tree$b)

ggplot(data = img_df_parte1, aes(x = x, y = y)) + 
  geom_point(colour = jpg_predito_lm) +
  labs(x = "x", y = "y", title = "Imagem com predição de modelo linear") +
  coord_fixed(ratio = 1) +
  theme_bw()

ggplot(data = img_df_parte1, aes(x = x, y = y)) + 
  geom_point(colour = jpg_predito_tree) +
  labs(x = "x", y = "y", title = "Imagem com predição de modelo de árvore de decisão") +
  coord_fixed(ratio = 1) +
  theme_bw()

```

# xadrez_colorido.jpg

Nessa parte o modelo tree teve um resultado melhor, porém nenhum dos dois modelos foi muito bem sucedido.

```{r}
library(ggplot2)
library(magrittr)
library(tidyr)
library(dplyr)
library(jpeg)
library(tree)

img <- readJPEG("images/xadrez_colorido.jpg")
img_dim <- dim(img)

# RGB para data.frame
img_df <- data.frame(
  x = rep(1:img_dim[2], each = img_dim[1]),
  y = rep(img_dim[1]:1, img_dim[2]),
  r = as.vector(img[,,1]),
  g = as.vector(img[,,2]),
  b = as.vector(img[,,3])
) %>%
  mutate(cor = rgb(r, g, b),
         id = 1:n())

# para reprodução
set.seed(1) 

# Parte 1) x, y, r, g
img_df_parte1 <- img_df %>% 
  sample_frac(3/5) %>% # separando 3/5 do banco
  mutate(b_backup = b, # backup do azul original
         b = 0, # retirando o azul da imagem
         cor = rgb(r, g, b)) # cor da imagem sem o azul

# Parte 2) x, y, r, g, b
img_df_parte2 <- img_df %>% filter(!id%in%img_df_parte1$id) # filtra as linhas que estão na Parte 1

# Imagem sem o azul
ggplot(data = img_df_parte1, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte1$cor) +
  labs(x = "x", y = "y", title = "Imagem sem B (azul)") +
  coord_fixed(ratio = 1) +
  theme_bw()

# Apenas o azul da imagem
ggplot(data = img_df_parte2, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte2$cor) +
  labs(x = "x", y = "y", title = "Imagem sem B (azul)") +
  coord_fixed(ratio = 1) +
  theme_bw()

# uma amostra de 500 pontos para a análise descritiva (usar o banco inteiro é desnecessário e demorado)
img_df_amostra <- img_df %>% 
  sample_n(500,replace = FALSE)

cor(img_df_amostra %>% 
      select (-cor, -id)) %>% 
  round(2)

pairs(~x + y + r + g + b, img_df_amostra )

modelo_lm <- lm(b ~ r, img_df_parte2)
modelo_tree <- tree( b ~ r, img_df_parte2)

predito_lm <- predict( modelo_lm, img_df_parte1)
predito_tree <- predict( modelo_tree, img_df_parte1)

img_df_parte1_lm <- img_df_parte1

img_df_parte1_lm$b <- predito_lm

img_df_parte1_lm$b[img_df_parte1_lm$b < 0] = 0

img_df_parte1_tree <- img_df_parte1

img_df_parte1_tree$b <- predito_tree

img_df_parte1_tree$b[img_df_parte1_tree$b < 0] = 0

mean(sum((img_df_parte1_lm$b_backup - img_df_parte1_lm$b)^2))

mean(sum((img_df_parte1_tree$b_backup - img_df_parte1_tree$b)^2))

jpg_predito_lm <- rgb(img_df_parte1_lm$r, img_df_parte1_lm$g, img_df_parte1_lm$b)

jpg_predito_tree <- rgb(img_df_parte1_tree$r, img_df_parte1_tree$g, img_df_parte1_tree$b)

ggplot(data = img_df_parte1, aes(x = x, y = y)) + 
  geom_point(colour = jpg_predito_lm) +
  labs(x = "x", y = "y", title = "Imagem com predição de modelo linear") +
  coord_fixed(ratio = 1) +
  theme_bw()

ggplot(data = img_df_parte1, aes(x = x, y = y)) + 
  geom_point(colour = jpg_predito_tree) +
  labs(x = "x", y = "y", title = "Imagem com predição de modelo de árvore de decisão") +
  coord_fixed(ratio = 1) +
  theme_bw()

```

