---
title: "Laboratório 2"
author: "Leonardo Alves Godoy"
date: "January 26, 2016"
output: html_document
---

# Parte 1

## CSV

```{r}
link_pnud_csv <-'https://www.dropbox.com/sh/c54yhhxuk82jdmp/AAAB9ykieoGp3_Jkisy3sPDsa/pnud_linux.csv?dl=1'

tmp <- tempfile()

download.file(link_pnud_csv, tmp, quiet = TRUE, method="wget")

pnud_csv <- read.table(tmp, sep=',', header = TRUE)

file.remove(tmp)

summary(pnud_csv[,1:10])

```

## TXT

```{r}
link_pnud_txt <-'https://www.dropbox.com/sh/c54yhhxuk82jdmp/AADRa6Q72y2N8RCn4mPNnwkGa/pnud_linux.txt?dl=1'

tmp <- tempfile()

download.file(link_pnud_txt, tmp, method="libcurl",quiet = TRUE)

pnud_txt <- read.table(tmp, sep=' ', header = TRUE)

file.remove(tmp)

summary(pnud_txt[,1:10])

```

## XLSX
```{r}
#install.packages("readxl")

library(readxl)

# A leitura do XLSX foi feita em um arquivo no disco, pois ao se fazer download diretamente pelo código do R ocorria falha na leitura.

path_xlsx <- '/home/leonardo/Documents/Estudos/R/pnud_linux.xlsx'

pnud_xlsx <- read_excel(path_xlsx)

summary(pnud_xlsx[,1:10])
```

## RDA

```{r}
link_pnud_rda <-'https://www.dropbox.com/sh/c54yhhxuk82jdmp/AAA4AGMtaUCg6AuQ8seJe3iYa/pnud.rda?dl=1'
tmp <- tempfile()

download.file(link_pnud_rda, tmp, quiet = TRUE, method="libcurl")

load(tmp)

pnud_rda <- d

file.remove(tmp)

summary(pnud_rda[,1:10])

```

## RDS


```{r}
link_pnud_rds <-'https://www.dropbox.com/sh/c54yhhxuk82jdmp/AAD8BJe5VBboOtamipv9Vg40a/pnud.rds?dl=1'

tmp <- tempfile()

download.file(link_pnud_rds, tmp, quiet = TRUE)

pnud_rds <- readRDS(tmp)

file.remove(tmp)

summary(pnud_rds[,1:10])

```

## SQLite

```{r}

#install.packages("dplyr")
#install.packages("RSQLite")

library(dplyr)

library(RSQLite)

link_pnud_sqlite <-'https://www.dropbox.com/sh/c54yhhxuk82jdmp/AACBc5rr109X8zNd3pe4Bfkda/pnud.sqlite?dl=1'

tmp <- tempfile()

download.file(link_pnud_sqlite, tmp, quiet = TRUE)

pnud_sqlite <- src_sqlite(tmp)

summary(pnud_rds[,1:10])

file.remove(tmp)

```

# Parte 2

## Carregamento do arquivo do pnud simplificado:
```{r}

library(dplyr)
library(httr)

link_pnud <- 'https://www.dropbox.com/s/seqctcl46qeemgu/pnud_simplificado.rds?dl=1'
tmp <- tempfile()
httr::GET(link_pnud, httr::write_disk(tmp))
pnud <- readRDS(tmp)
file.remove(tmp)
```

## Seis municípios com os maiores IDH municipais em 2010:

```{r}

pnud_csv %>% 
  select( municipio, ufn,  ano, gini, idhm) %>%
  filter( ano == 2010 ) %>%
  mutate( idhm_p = paste(round( idhm * 100, 1) , "%" ) ) %>%
  arrange( desc(idhm) ) %>%
  tbl_df() %>%
  head (n = 6 ) 
```

## Unidade federativa com menor expectativa de vida média, ponderada pela população dos municípios em 2000:

```{r}
pnud_csv %>% 
  select( municipio, ufn,  ano, gini, idhm, espvida, popt) %>%
  filter( ano == 2000) %>% 
  group_by( ufn ) %>% 
  summarise(  x = sum(espvida*popt) / sum(popt)) %>% 
  arrange (desc(x)) %>% 
  head(1)
```

## Municípios outliers com relação ao índice de Gini em 1991 e em 2010 ( aqueles que estão acima ou abaixo da média por dois desvios padrão):
```{r}

municipios_outliers_1991 <- pnud %>% 
  select( municipio,ano, gini) %>%
  filter( ano == 1991 & ( gini > mean(gini) + 2*sd(gini)) | gini < mean(gini) - 2*sd(gini))

municipios_outliers_2010 <- pnud %>% 
  select( municipio,ano, gini) %>%
  filter( ano == 2010 & ( gini > mean(gini) + 2*sd(gini)) | gini < mean(gini) - 2*sd(gini))

municipios_outliers_1991

head(municipios_outliers_2010)

```

